version: '3.8'

services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/usr/src/app
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy  # Espera o MySQL estar saudável

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    volumes:
      - db_data:/var/lib/mysql  # Mapeamento de volume do MySQL
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Arquivo de inicialização SQL no MySQL
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app  # Garante que o app esteja iniciado antes do nginx

networks:
  app-network:
    driver: bridge

volumes:
  db_data:  # Define o volume para o banco de dados
